namespace AIHubRouter.Core.Tests;

internal readonly record struct TestCase(string Name, Action Body);

internal static class TestCatalog
{
    public static IReadOnlyList<TestCase> All { get; } = Create(
        new TestCase("Bearer token normalization", CoreTestCases.TestBearerNormalization),
        new TestCase("Token extraction from cookie", CoreTestCases.TestCookieTokenExtraction),
        new TestCase("Test catalog rejects duplicate names", CoreTestCases.TestCatalogRejectsDuplicateNames),
        new TestCase("Test catalog snapshots input", CoreTestCases.TestCatalogSnapshotsInput),
        new TestCase("Lowest available authorized group", CoreTestCases.TestLowestAvailableGroup),
        new TestCase("User rate override", CoreTestCases.TestUserRateOverride),
        new TestCase("Availability threshold", CoreTestCases.TestAvailabilityThreshold),
        new TestCase("Provider warnings deserialize", CoreTestCases.TestProviderWarningsDeserialize),
        new TestCase("Null provider warnings are tolerated", CoreTestCases.TestNullProviderWarningsAreTolerated),
        new TestCase("Provider last-call aliases deserialize", CoreTestCases.TestProviderLastCallAliasesDeserialize),
        new TestCase("Twenty-minute provider metrics use medians", CoreTestCases.TestRollingProviderMetricsUseMedians),
        new TestCase("Rolling provider metrics discard samples outside the window", CoreTestCases.TestRollingProviderMetricsDiscardExpiredSamples),
        new TestCase("Rolling provider metrics clear account history", CoreTestCases.TestRollingProviderMetricsClearHistory),
        new TestCase("Rolling provider metrics are stable for duplicate groups", CoreTestCases.TestRollingProviderMetricsAreStableForDuplicateGroups),
        new TestCase("Adaptive constants match supplied economics", CoreTestCases.TestAdaptiveConstants),
        new TestCase("Adaptive preference follows interval boundaries", CoreTestCases.TestAdaptivePreferenceBoundaries),
        new TestCase("Current-group interval uses latest provider call", CoreTestCases.TestCurrentGroupIntervalResolution),
        new TestCase("Missing call time retains base preference", CoreTestCases.TestMissingCallTimeRetainsBasePreference),
        new TestCase("Adaptive penalty uses new multiplier", CoreTestCases.TestAdaptivePenalty),
        new TestCase("Adaptive completion time includes TTFT", CoreTestCases.TestAdaptiveCompletionTime),
        new TestCase("Adaptive net saving subtracts context penalty", CoreTestCases.TestAdaptiveNetSaving),
        new TestCase("Adaptive cost accepts positive saving", CoreTestCases.TestAdaptiveCostAcceptsPositiveSaving),
        new TestCase("Adaptive cost rejects slow candidate", CoreTestCases.TestAdaptiveCostRejectsSlowCandidate),
        new TestCase("Adaptive balanced requires all safeguards", CoreTestCases.TestAdaptiveBalancedSafeguards),
        new TestCase("Adaptive speed accepts generation boost", CoreTestCases.TestAdaptiveSpeedAcceptsGenerationBoost),
        new TestCase("Adaptive speed accepts end-to-end gain", CoreTestCases.TestAdaptiveSpeedAcceptsEndToEndGain),
        new TestCase("Balanced deadline uses explicit output budget", CoreTestCases.TestBalancedDeadlineUsesExplicitOutputBudget),
        new TestCase("Balanced deadline keeps current feasible node", CoreTestCases.TestBalancedDeadlineKeepsCurrentNode),
        new TestCase("Balanced deadline switches to cheapest feasible node", CoreTestCases.TestBalancedDeadlineChoosesCheapestFeasibleNode),
        new TestCase("Balanced deadline cold start chooses cheapest feasible node", CoreTestCases.TestBalancedDeadlineColdStart),
        new TestCase("Balanced deadline honors user soft tolerance", CoreTestCases.TestBalancedDeadlineHonorsSoftTolerance),
        new TestCase("Balanced deadline zero falls back to economy", CoreTestCases.TestBalancedDeadlineZeroFallsBackToEconomy),
        new TestCase("Adaptive short task is protected outside cost", CoreTestCases.TestAdaptiveShortTaskProtection),
        new TestCase("Adaptive invalid performance cannot switch", CoreTestCases.TestAdaptiveInvalidPerformance),
        new TestCase("Adaptive invalid old performance cannot satisfy relative time", CoreTestCases.TestAdaptiveInvalidOldPerformance),
        new TestCase("Warning provider remains eligible", CoreTestCases.TestWarningProviderRemainsEligible),
        new TestCase("Latest unavailable state remains ineligible", CoreTestCases.TestLatestUnavailableStateRemainsIneligible),
        new TestCase("Warning presentation excludes server message", CoreTestCases.TestWarningPresentationExcludesServerMessage),
        new TestCase("Warning decoration requires routable latest state", CoreTestCases.TestWarningDecorationRequiresRoutableLatestState),
        new TestCase("Routing presentation preserves availability threshold", CoreTestCases.TestRoutingPresentationPreservesAvailabilityThreshold),
        new TestCase("Routing presentation rejects invalid effective rate", CoreTestCases.TestRoutingPresentationRejectsInvalidEffectiveRate),
        new TestCase("Stale status rejection", CoreTestCases.TestStaleStatusRejection),
        new TestCase("Routing preferences default to Win32-compatible values", CoreTestCases.TestRoutingPreferenceDefaults),
        new TestCase("Routing preferences roundtrip", CoreTestCases.TestRoutingPreferenceRoundtrip),
        new TestCase("Balanced mode buys meaningful latency", CoreTestCases.TestBalancedModeBuysLatency),
        new TestCase("Balanced mode keeps price for moderate speed gap", CoreTestCases.TestBalancedModeKeepsPriceForModerateSpeedGap),
        new TestCase("Economy mode protects price", CoreTestCases.TestEconomyModeProtectsPrice),
        new TestCase("Speed mode accepts larger price premium", CoreTestCases.TestSpeedModeAcceptsLargerPremium),
        new TestCase("Selective policy preserves local routing weights", CoreTestCases.TestSelectivePolicyPreservesLocalWeights),
        new TestCase("Cost mode proposes strict cheapest candidate", CoreTestCases.TestCostModeProposesCheapest),
        new TestCase("Cost mode falls back when cheapest TTFT is unknown", CoreTestCases.TestCostModeFallsBackWhenCheapestTtftIsUnknown),
        new TestCase("Economy remains strict during frequent calls", CoreTestCases.TestFrequentCallsOverrideEconomy),
        new TestCase("Idle calls override speed with cost", CoreTestCases.TestIdleCallsOverrideSpeed),
        new TestCase("Adaptive rejection keeps current group", CoreTestCases.TestAdaptiveRejectionKeepsCurrentGroup),
        new TestCase("Adaptive acceptance updates selected Keys", CoreTestCases.TestAdaptiveAcceptanceUpdatesKeys),
        new TestCase("Adaptive traversal finds an accepted candidate beyond weighted winner", CoreTestCases.TestAdaptiveTraversalFindsAcceptedCandidateBeyondWeightedWinner),
        new TestCase("Adaptive rankings follow accepted algorithm order", CoreTestCases.TestAdaptiveRankingsFollowAcceptedAlgorithmOrder),
        new TestCase("Initial and invalid routes recover immediately", CoreTestCases.TestAdaptiveRecoveryBypassesGuard),
        new TestCase("Missing latency ranks last", CoreTestCases.TestMissingLatencyRanksLast),
        new TestCase("Invalid measurements are excluded", CoreTestCases.TestInvalidMeasurementsAreExcluded),
        new TestCase("Extreme latency scores stay finite", CoreTestCases.TestExtremeLatencyScoresStayFinite),
        new TestCase("Zero multiplier remains free", CoreTestCases.TestZeroMultiplierWindow),
        new TestCase("Initial route has an explainable reason", CoreTestCases.TestInitialRouteDecision),
        new TestCase("Preview and simulation share the initial route decision", CoreTestCases.TestPreviewAndSimulationShareInitialDecision),
        new TestCase("Adaptive speed winner switches after guard", CoreTestCases.TestWeightedSpeedWinnerSwitchesImmediately),
        new TestCase("Already optimal route does not switch", CoreTestCases.TestAlreadyOptimalRouteDecision),
        new TestCase("Invalid current route switches", CoreTestCases.TestInvalidCurrentRouteDecision),
        new TestCase("No candidate keeps route state", CoreTestCases.TestNoCandidateDecision),
        new TestCase("Route state persists atomically", CoreTestCases.TestRouteStateRoundtrip),
        new TestCase("Unreadable route state resets safely", CoreTestCases.TestUnreadableRouteStateResets),
        new TestCase("Dry run never updates a Key", CoreTestCases.TestDryRunNeverUpdatesKey),
        new TestCase("Account data is cached but monitor data is fresh", CoreTestCases.TestAccountDataCache),
        new TestCase("Routing result exposes cached user rates", CoreTestCases.TestRoutingResultExposesUserRates),
        new TestCase("Forced refresh bypasses account cache", CoreTestCases.TestForcedAccountRefresh),
        new TestCase("Business authentication failure retries once", CoreTestCases.TestBusinessAuthenticationRetry),
        new TestCase("Network failure never triggers login", CoreTestCases.TestRoutingNetworkFailureDoesNotLogin),
        new TestCase("Explicit empty Key selection is rejected", CoreTestCases.TestRoutingRejectsEmptySelection),
        new TestCase("Successful updates persist target state", CoreTestCases.TestSuccessfulRoutePersistsState),
        new TestCase("Partial update failure clears route certainty", CoreTestCases.TestPartialFailureClearsState),
        new TestCase("Already optimal cycle reports selected Keys", CoreTestCases.TestAlreadyOptimalReportsSelectedKeys),
        new TestCase("Mixed selected groups reconcile to target", CoreTestCases.TestMixedSelectedGroupsReconcile),
        new TestCase("Audit log writes valid JSON and rotates safely", CoreTestCases.TestAuditLogWritesValidJsonAndRotates),
        new TestCase("Publish script checks native exit codes", CoreTestCases.TestPublishScriptChecksNativeExitCodes),
        new TestCase("Encrypted settings roundtrip", CoreTestCases.TestEncryptedSettingsRoundtrip),
        new TestCase("Usable access token is reused", CoreTestCases.TestUsableAccessTokenIsReused),
        new TestCase("Expired access token refreshes first", CoreTestCases.TestExpiredAccessTokenRefreshesFirst),
        new TestCase("Rejected refresh falls back to login", CoreTestCases.TestRejectedRefreshFallsBackToLogin),
        new TestCase("Refresh API code falls back to login", CoreTestCases.TestRefreshApiCodeFallsBackToLogin),
        new TestCase("Refresh network failure does not log in", CoreTestCases.TestRefreshNetworkFailureDoesNotLogIn),
        new TestCase("Authentication API code is classified", CoreTestCases.TestAuthenticationApiCodeIsClassified),
        new TestCase("Login endpoint maps session", CoreTestCases.TestLoginEndpointMapsSession),
        new TestCase("Refresh endpoint maps rotated session", CoreTestCases.TestRefreshEndpointMapsRotatedSession),
        new TestCase("Refresh keeps token when server omits rotation", CoreTestCases.TestRefreshKeepsTokenWhenServerOmitsRotation),
        new TestCase("Authentication error hides server message", CoreTestCases.TestAuthenticationErrorHidesServerMessage),
        new TestCase("Business error hides server message", CoreTestCases.TestBusinessErrorHidesServerMessage),
        new TestCase("Authentication statuses have safe diagnostics", CoreTestCases.TestAuthenticationStatusesHaveSafeDiagnostics),
        new TestCase("Business authentication statuses keep business diagnostics", CoreTestCases.TestBusinessAuthenticationStatusesKeepBusinessDiagnostics),
        new TestCase("Malformed authentication responses retain endpoint context", CoreTestCases.TestMalformedAuthenticationResponsesRetainEndpointContext),
        new TestCase("Unknown errors do not expose credential text", CoreTestCases.TestUnknownErrorsDoNotExposeCredentialText),
        new TestCase("Interactive login requirement is rejected", CoreTestCases.TestInteractiveLoginRequirementIsRejected),
        new TestCase("Empty key selection roundtrips", CoreTestCases.TestEmptyKeySelectionRoundtrips),
        new TestCase("First key selection chooses first active key", CoreTestCases.TestFirstKeySelectionChoosesFirstActiveKey),
        new TestCase("Initialized empty key selection stays empty", CoreTestCases.TestInitializedEmptyKeySelectionStaysEmpty));

    public static IReadOnlyList<TestCase> Create(params TestCase[] tests)
    {
        var names = new HashSet<string>(StringComparer.Ordinal);
        foreach (var test in tests)
        {
            if (!names.Add(test.Name))
            {
                throw new InvalidOperationException($"Duplicate test name: {test.Name}.");
            }
        }

        return Array.AsReadOnly(tests.ToArray());
    }
}
