namespace AIHubRouter.Core.Tests;

internal readonly record struct TestCase(string Name, Action Body);

internal static class TestCatalog
{
    public static IReadOnlyList<TestCase> All { get; } = Create(
        new TestCase("Bearer token normalization", CoreTestCases.TestBearerNormalization),
        new TestCase("Token extraction from cookie", CoreTestCases.TestCookieTokenExtraction),
        new TestCase("Test catalog rejects duplicate names", CoreTestCases.TestCatalogRejectsDuplicateNames),
        new TestCase("Test catalog snapshots input", CoreTestCases.TestCatalogSnapshotsInput),
        new TestCase("Lowest available authorized group", CoreTestCases.TestLowestAvailableGroup),
        new TestCase("User rate override", CoreTestCases.TestUserRateOverride),
        new TestCase("Availability threshold", CoreTestCases.TestAvailabilityThreshold),
        new TestCase("Exact group blacklist excludes route candidate", CoreTestCases.TestExactGroupBlocklistExcludesRouteCandidate),
        new TestCase("Blacklist patterns match node fields ignoring case", CoreTestCases.TestBlocklistPatternsMatchNodeFieldsIgnoringCase),
        new TestCase("Unmatched blacklist rule keeps candidate", CoreTestCases.TestUnmatchedBlocklistRuleKeepsCandidate),
        new TestCase("Blacklist settings roundtrip", CoreTestCases.TestBlocklistSettingsRoundtrip),
        new TestCase("Active probe measures first content token", CoreTestCases.TestActiveProbeMeasuresFirstContentToken),
        new TestCase("Active probe checks selected Key without changing group", CoreTestCases.TestActiveProbeChecksSelectedKeyWithoutChangingGroup),
        new TestCase("Active probe health failure does not change selected Key group", CoreTestCases.TestActiveProbeHealthFailureDoesNotChangeSelectedKeyGroup),
        new TestCase("Active probe targets then restores dedicated Key", CoreTestCases.TestActiveProbeTargetsThenRestoresDedicatedKey),
        new TestCase("Active probe rejects mismatched measurement identity", CoreTestCases.TestActiveProbeRejectsMismatchedMeasurementIdentity),
        new TestCase("Active probe restores test Key after cycle", CoreTestCases.TestActiveProbeRestoresTestKeyAfterCycle),
        new TestCase("Active probe restores test Key after failure", CoreTestCases.TestActiveProbeRestoresTestKeyAfterFailure),
        new TestCase("Active probe restores test Key after canceled remote switch", CoreTestCases.TestActiveProbeRestoresTestKeyAfterCanceledRemoteSwitch),
        new TestCase("Active probe surfaces restore timeout after cancellation", CoreTestCases.TestActiveProbeSurfacesRestoreTimeoutAfterCancellation),
        new TestCase("Active probe cycle rejects unconfirmed forward move", CoreTestCases.TestActiveProbeCycleRejectsUnconfirmedForwardMove),
        new TestCase("Active probe cycle rejects unconfirmed restore", CoreTestCases.TestActiveProbeCycleRejectsUnconfirmedRestore),
        new TestCase("Active probe metrics preserve reported latency", CoreTestCases.TestActiveProbeMetricsPreserveReportedLatency),
        new TestCase("Active probe observations track failure and recovery", CoreTestCases.TestActiveProbeObservationsTrackFailureAndRecovery),
        new TestCase("Active probe late expired sample cannot pollute median", CoreTestCases.TestActiveProbeLateExpiredSampleCannotPolluteMedian),
        new TestCase("Active probe observation validates input", CoreTestCases.TestActiveProbeObservationValidation),
        new TestCase("Active probe policy TTL uses configured interval", CoreTestCases.TestActiveProbePolicyTtlUsesConfiguredInterval),
        new TestCase("Active probe HTTP 200 JSON error is structured and safe", CoreTestCases.TestActiveProbeHttp200JsonErrorIsStructuredAndSafe),
        new TestCase("Active probe structured JSON suffix error is rejected", CoreTestCases.TestActiveProbeStructuredJsonSuffixErrorIsRejected),
        new TestCase("Active probe SSE error is structured and safe", CoreTestCases.TestActiveProbeSseErrorIsStructuredAndSafe),
        new TestCase("Active probe malformed data never becomes success", CoreTestCases.TestActiveProbeMalformedDataNeverBecomesSuccess),
        new TestCase("Active probe protocol exception redacts credential-shaped codes", CoreTestCases.TestActiveProbeProtocolExceptionRedactsCredentialShapedCodes),
        new TestCase("Active probe non-success HTTP response preserves status and redacts body", CoreTestCases.TestActiveProbeNonSuccessHttpResponsePreservesStatusAndRedactsBody),
        new TestCase("Active probe non-success JSON global failure preserves status", CoreTestCases.TestActiveProbeNonSuccessJsonGlobalFailurePreservesStatus),
        new TestCase("Active probe service returns sanitized recoverable details", CoreTestCases.TestActiveProbeServiceReturnsSanitizedRecoverableDetails),
        new TestCase("Active probe service propagates global failures", CoreTestCases.TestActiveProbeServicePropagatesGlobalFailures),
        new TestCase("Active probe service propagates account failures and cancellation", CoreTestCases.TestActiveProbeServicePropagatesAccountFailuresAndCancellation),
        new TestCase("Active probe selected-Key cancellation wins recoverable failure", CoreTestCases.TestActiveProbeSelectedKeyCancellationWinsRecoverableFailure),
        new TestCase("Active probe cycle cancellation wins recoverable failure and restores Key", CoreTestCases.TestActiveProbeCycleCancellationWinsRecoverableFailureAndRestoresKey),
        new TestCase("Active probe service propagates local configuration failures", CoreTestCases.TestActiveProbeServicePropagatesLocalConfigurationFailures),
        new TestCase("Active probe Key persists only in credentials", CoreTestCases.TestActiveProbeKeyPersistsOnlyInCredentials),
        new TestCase("Session persistence retains active probe Key", CoreTestCases.TestSessionPersistenceRetainsActiveProbeKey),
        new TestCase("Provider warnings deserialize", CoreTestCases.TestProviderWarningsDeserialize),
        new TestCase("Null provider warnings are tolerated", CoreTestCases.TestNullProviderWarningsAreTolerated),
        new TestCase("Provider last-call aliases deserialize", CoreTestCases.TestProviderLastCallAliasesDeserialize),
        new TestCase("Provider metrics default to thirty minutes", CoreTestCases.TestRollingProviderMetricsDefaultToThirtyMinutes),
        new TestCase("Thirty-minute provider metrics use medians", CoreTestCases.TestRollingProviderMetricsUseMedians),
        new TestCase("Rolling provider metrics discard samples outside the window", CoreTestCases.TestRollingProviderMetricsDiscardExpiredSamples),
        new TestCase("Rolling provider metrics use latest current state", CoreTestCases.TestRollingProviderMetricsUseLatestCurrentState),
        new TestCase("Rolling provider metrics ignore out-of-order current state", CoreTestCases.TestRollingProviderMetricsIgnoreOutOfOrderCurrentState),
        new TestCase("Rolling provider metrics survive probe watermark advance", CoreTestCases.TestRollingProviderMetricsSurviveProbeWatermarkAdvance),
        new TestCase("Rolling provider metrics clear account history", CoreTestCases.TestRollingProviderMetricsClearHistory),
        new TestCase("Rolling provider metrics are stable for duplicate groups", CoreTestCases.TestRollingProviderMetricsAreStableForDuplicateGroups),
        new TestCase("Rolling provider metrics use latest duplicate state", CoreTestCases.TestRollingProviderMetricsUseLatestDuplicateState),
        new TestCase("Rolling provider metrics expose conservative performance", CoreTestCases.TestRollingProviderMetricsExposeConservativePerformance),
        new TestCase("Rolling provider metrics normalize raw reliability", CoreTestCases.TestRollingProviderMetricsNormalizeRawReliability),
        new TestCase("Adaptive constants match supplied economics", CoreTestCases.TestAdaptiveConstants),
        new TestCase("Adaptive preference follows interval boundaries", CoreTestCases.TestAdaptivePreferenceBoundaries),
        new TestCase("Current-group interval uses latest provider call", CoreTestCases.TestCurrentGroupIntervalResolution),
        new TestCase("Missing call time retains base preference", CoreTestCases.TestMissingCallTimeRetainsBasePreference),
        new TestCase("Adaptive penalty uses new multiplier", CoreTestCases.TestAdaptivePenalty),
        new TestCase("Adaptive completion time includes TTFT", CoreTestCases.TestAdaptiveCompletionTime),
        new TestCase("Adaptive net saving subtracts context penalty", CoreTestCases.TestAdaptiveNetSaving),
        new TestCase("Adaptive cost accepts positive saving", CoreTestCases.TestAdaptiveCostAcceptsPositiveSaving),
        new TestCase("Adaptive cost rejects slow candidate", CoreTestCases.TestAdaptiveCostRejectsSlowCandidate),
        new TestCase("Adaptive balanced requires all safeguards", CoreTestCases.TestAdaptiveBalancedSafeguards),
        new TestCase("Adaptive speed accepts generation boost", CoreTestCases.TestAdaptiveSpeedAcceptsGenerationBoost),
        new TestCase("Adaptive speed accepts end-to-end gain", CoreTestCases.TestAdaptiveSpeedAcceptsEndToEndGain),
        new TestCase("Adaptive speed needs reliable performance samples", CoreTestCases.TestAdaptiveSpeedNeedsReliablePerformanceSamples),
        new TestCase("Balanced deadline uses explicit output budget", CoreTestCases.TestBalancedDeadlineUsesExplicitOutputBudget),
        new TestCase("Balanced convenience overload uses default output budget", CoreTestCases.TestBalancedConvenienceOverloadUsesDefaultOutputBudget),
        new TestCase("Coordinator uses default Balanced output budget", CoreTestCases.TestCoordinatorUsesDefaultBalancedOutputBudgetWhenOmitted),
        new TestCase("Legacy adaptive context position remains compatible", CoreTestCases.TestLegacyAdaptiveContextPositionRemainsCompatible),
        new TestCase("Legacy Coordinator position remains compatible", CoreTestCases.TestLegacyCoordinatorPositionRemainsCompatible),
        new TestCase("Balanced deadline keeps current feasible node", CoreTestCases.TestBalancedDeadlineKeepsCurrentNode),
        new TestCase("Balanced deadline switches to cheapest feasible node", CoreTestCases.TestBalancedDeadlineChoosesCheapestFeasibleNode),
        new TestCase("Balanced deadline cold start chooses cheapest feasible node", CoreTestCases.TestBalancedDeadlineColdStart),
        new TestCase("Balanced deadline cold start falls back to fastest route", CoreTestCases.TestBalancedDeadlineColdStartFallsBackToFastestRoute),
        new TestCase("Balanced deadline honors user soft tolerance", CoreTestCases.TestBalancedDeadlineHonorsSoftTolerance),
        new TestCase("Balanced mode without countdown uses deadline", CoreTestCases.TestBalancedWithoutCountdownUsesDeadline),
        new TestCase("Balanced deadline uses conservative performance", CoreTestCases.TestBalancedDeadlineUsesConservativePerformance),
        new TestCase("Balanced deadline invalid current is forced recovery", CoreTestCases.TestBalancedDeadlineInvalidCurrentIsForcedRecovery),
        new TestCase("Balanced deadline switch uses policy hysteresis", CoreTestCases.TestBalancedDeadlineSwitchUsesPolicyHysteresis),
        new TestCase("Adaptive short task is protected outside cost", CoreTestCases.TestAdaptiveShortTaskProtection),
        new TestCase("Adaptive invalid performance cannot switch", CoreTestCases.TestAdaptiveInvalidPerformance),
        new TestCase("Adaptive invalid old performance cannot satisfy relative time", CoreTestCases.TestAdaptiveInvalidOldPerformance),
        new TestCase("Warning provider remains eligible", CoreTestCases.TestWarningProviderRemainsEligible),
        new TestCase("Latest unavailable state remains ineligible", CoreTestCases.TestLatestUnavailableStateRemainsIneligible),
        new TestCase("Warning presentation excludes server message", CoreTestCases.TestWarningPresentationExcludesServerMessage),
        new TestCase("Warning decoration requires routable latest state", CoreTestCases.TestWarningDecorationRequiresRoutableLatestState),
        new TestCase("Routing presentation preserves availability threshold", CoreTestCases.TestRoutingPresentationPreservesAvailabilityThreshold),
        new TestCase("Routing presentation rejects invalid effective rate", CoreTestCases.TestRoutingPresentationRejectsInvalidEffectiveRate),
        new TestCase("Stale status remains routable with downweighted presentation", CoreTestCases.TestStaleStatusRemainsRoutable),
        new TestCase("Routing preferences default to Win32-compatible values", CoreTestCases.TestRoutingPreferenceDefaults),
        new TestCase("Routing preferences roundtrip", CoreTestCases.TestRoutingPreferenceRoundtrip),
        new TestCase("Balanced mode buys meaningful latency", CoreTestCases.TestBalancedModeBuysLatency),
        new TestCase("Balanced mode keeps price for moderate speed gap", CoreTestCases.TestBalancedModeKeepsPriceForModerateSpeedGap),
        new TestCase("Economy mode protects price", CoreTestCases.TestEconomyModeProtectsPrice),
        new TestCase("Speed mode accepts larger price premium", CoreTestCases.TestSpeedModeAcceptsLargerPremium),
        new TestCase("Evidence weight follows decay boundaries", CoreTestCases.TestEvidenceWeightDecayBoundaries),
        new TestCase("Route candidates default evidence weight", CoreTestCases.TestRouteCandidateDefaultsEvidenceWeight),
        new TestCase("Routing public models preserve four-field compatibility", CoreTestCases.TestRoutingPublicModelsPreserveFourFieldCompatibility),
        new TestCase("Routing status age defaults to thirty minutes", CoreTestCases.TestRoutingStatusAgeDefaultsToThirtyMinutes),
        new TestCase("Routing accepts stale or performance evidence", CoreTestCases.TestRoutingAcceptsStaleOrPerformanceEvidence),
        new TestCase("Routing uses latest evidence timestamp", CoreTestCases.TestRoutingUsesLatestEvidenceTimestamp),
        new TestCase("Stale positive benefits are downweighted", CoreTestCases.TestStalePositiveBenefitsAreDownweighted),
        new TestCase("Evidence decay preserves penalties", CoreTestCases.TestEvidenceDecayPreservesPenalties),
        new TestCase("Reliability delta contributes to score", CoreTestCases.TestReliabilityDeltaContributesToScore),
        new TestCase("Reliability weight remains bounded", CoreTestCases.TestReliabilityWeightConstant),
        new TestCase("Reliability score normalizes raw rates", CoreTestCases.TestReliabilityScoreNormalizesRawRates),
        new TestCase("Reliability eligibility and tie breaks normalize raw rates", CoreTestCases.TestReliabilityEligibilityAndTieBreaksNormalizeRawRates),
        new TestCase("Fresh active probe failure is excluded at TTL boundary", CoreTestCases.TestFreshActiveProbeFailureIsExcludedAtTtlBoundary),
        new TestCase("Expired active probe failure is neutral", CoreTestCases.TestExpiredActiveProbeFailureIsNeutral),
        new TestCase("Fresh active probe success provides freshness evidence", CoreTestCases.TestFreshActiveProbeSuccessProvidesFreshnessEvidence),
        new TestCase("Expired active probe success restores provider latency", CoreTestCases.TestExpiredActiveProbeSuccessRestoresProviderLatency),
        new TestCase("Selective policy preserves local routing weights", CoreTestCases.TestSelectivePolicyPreservesLocalWeights),
        new TestCase("Cost mode proposes strict cheapest candidate", CoreTestCases.TestCostModeProposesCheapest),
        new TestCase("Cost mode falls back when cheapest TTFT is unknown", CoreTestCases.TestCostModeFallsBackWhenCheapestTtftIsUnknown),
        new TestCase("First Token keeps stale provider eligible", CoreTestCases.TestFirstTokenKeepsStaleProviderEligible),
        new TestCase("Stale First Token candidates participate in ranking", CoreTestCases.TestStaleFirstTokenCandidatesParticipateInRanking),
        new TestCase("Forced group overrides policy until unavailable", CoreTestCases.TestForcedGroupOverridesRoutingPolicyUntilUnavailable),
        new TestCase("Releasing forced group preserves policy dwell baseline", CoreTestCases.TestReleasingForcedGroupPreservesPolicyDwellBaseline),
        new TestCase("Economy remains strict during frequent calls", CoreTestCases.TestFrequentCallsOverrideEconomy),
        new TestCase("Idle calls override speed with cost", CoreTestCases.TestIdleCallsOverrideSpeed),
        new TestCase("Adaptive rejection keeps current group", CoreTestCases.TestAdaptiveRejectionKeepsCurrentGroup),
        new TestCase("Adaptive acceptance updates selected Keys", CoreTestCases.TestAdaptiveAcceptanceUpdatesKeys),
        new TestCase("Adaptive traversal finds an accepted candidate beyond weighted winner", CoreTestCases.TestAdaptiveTraversalFindsAcceptedCandidateBeyondWeightedWinner),
        new TestCase("Adaptive rankings follow accepted algorithm order", CoreTestCases.TestAdaptiveRankingsFollowAcceptedAlgorithmOrder),
        new TestCase("Initial and invalid routes recover immediately", CoreTestCases.TestAdaptiveRecoveryBypassesGuard),
        new TestCase("Policy switch needs a stable candidate", CoreTestCases.TestPolicySwitchNeedsStableCandidate),
        new TestCase("Policy switch requires dwell and completed evaluations", CoreTestCases.TestPolicySwitchRequiresDwellAndCompletedEvaluations),
        new TestCase("Forced recovery bypasses policy hysteresis", CoreTestCases.TestForcedRecoveryBypassesPolicyHysteresis),
        new TestCase("Missing latency ranks last", CoreTestCases.TestMissingLatencyRanksLast),
        new TestCase("Invalid measurements are excluded", CoreTestCases.TestInvalidMeasurementsAreExcluded),
        new TestCase("Extreme latency scores stay finite", CoreTestCases.TestExtremeLatencyScoresStayFinite),
        new TestCase("Zero multiplier remains free", CoreTestCases.TestZeroMultiplierWindow),
        new TestCase("Initial route has an explainable reason", CoreTestCases.TestInitialRouteDecision),
        new TestCase("Preview and simulation share the initial route decision", CoreTestCases.TestPreviewAndSimulationShareInitialDecision),
        new TestCase("Adaptive speed winner switches after guard", CoreTestCases.TestWeightedSpeedWinnerSwitchesImmediately),
        new TestCase("Already optimal route does not switch", CoreTestCases.TestAlreadyOptimalRouteDecision),
        new TestCase("Invalid current route switches", CoreTestCases.TestInvalidCurrentRouteDecision),
        new TestCase("No candidate keeps route state", CoreTestCases.TestNoCandidateDecision),
        new TestCase("Route state persists atomically", CoreTestCases.TestRouteStateRoundtrip),
        new TestCase("Unreadable route state resets safely", CoreTestCases.TestUnreadableRouteStateResets),
        new TestCase("RoutingService retains seven-parameter constructor", CoreTestCases.TestRoutingServiceRetainsSevenParameterConstructor),
        new TestCase("Dry run never updates a Key", CoreTestCases.TestDryRunNeverUpdatesKey),
        new TestCase("Account data is cached but monitor data is fresh", CoreTestCases.TestAccountDataCache),
        new TestCase("Routing result exposes cached user rates", CoreTestCases.TestRoutingResultExposesUserRates),
        new TestCase("Forced refresh bypasses account cache", CoreTestCases.TestForcedAccountRefresh),
        new TestCase("Business authentication failure retries once", CoreTestCases.TestBusinessAuthenticationRetry),
        new TestCase("Network failure never triggers login", CoreTestCases.TestRoutingNetworkFailureDoesNotLogin),
        new TestCase("Explicit empty Key selection is rejected", CoreTestCases.TestRoutingRejectsEmptySelection),
        new TestCase("Successful updates persist target state", CoreTestCases.TestSuccessfulRoutePersistsState),
        new TestCase("Partial update failure clears route certainty", CoreTestCases.TestPartialFailureClearsState),
        new TestCase("Already optimal cycle reports selected Keys", CoreTestCases.TestAlreadyOptimalReportsSelectedKeys),
        new TestCase("Mixed selected groups reconcile to target", CoreTestCases.TestMixedSelectedGroupsReconcile),
        new TestCase("Active probe Key is excluded from routing", CoreTestCases.TestActiveProbeKeyIsExcludedFromRouting),
        new TestCase("Routing preflight restores health Key before business write", CoreTestCases.TestRoutingPreflightRestoresHealthKeyBeforeBusinessWrite),
        new TestCase("Routing preflight skips dry-run", CoreTestCases.TestRoutingPreflightSkipsDryRun),
        new TestCase("Routing preflight falls back after recoverable failure", CoreTestCases.TestRoutingPreflightFallsBackAfterRecoverableFailure),
        new TestCase("Routing preflight all failures save only final state", CoreTestCases.TestRoutingPreflightAllFailuresSaveOnlyFinalState),
        new TestCase("Routing preflight restore failure blocks business writes", CoreTestCases.TestRoutingPreflightRestoreFailureBlocksBusinessWrites),
        new TestCase("Routing preflight rejects unconfirmed forward move", CoreTestCases.TestRoutingPreflightRejectsUnconfirmedForwardMove),
        new TestCase("Routing preflight rejects unconfirmed restore", CoreTestCases.TestRoutingPreflightRejectsUnconfirmedRestore),
        new TestCase("Routing preflight cancellation restores without health failure", CoreTestCases.TestRoutingPreflightCancellationRestoresWithoutHealthFailure),
        new TestCase("Routing preflight health Key already on target avoids control-plane move", CoreTestCases.TestRoutingPreflightHealthKeyAlreadyOnTargetAvoidsControlPlaneMove),
        new TestCase("Routing preflight skips no target and no required business write", CoreTestCases.TestRoutingPreflightSkipsNoTargetAndNoRequiredBusinessWrite),
        new TestCase("Routing preflight uses cached health at inclusive TTL boundary", CoreTestCases.TestRoutingPreflightUsesCachedHealthAtInclusiveTtlBoundary),
        new TestCase("Routing preflight reconciles mixed business groups without switch", CoreTestCases.TestRoutingPreflightReconcilesMixedBusinessGroupsWithoutSwitch),
        new TestCase("Routing preflight invalid configuration fails closed", CoreTestCases.TestRoutingPreflightInvalidConfigurationFailsClosed),
        new TestCase("Routing preflight account errors propagate without node failure", CoreTestCases.TestRoutingPreflightAccountErrorsPropagateWithoutNodeFailure),
        new TestCase("Routing preflight ignores foreign platform cached success", CoreTestCases.TestRoutingPreflightIgnoresForeignPlatformCachedSuccess),
        new TestCase("Audit log writes valid JSON and rotates safely", CoreTestCases.TestAuditLogWritesValidJsonAndRotates),
        new TestCase("Publish script checks native exit codes", CoreTestCases.TestPublishScriptChecksNativeExitCodes),
        new TestCase("Encrypted settings roundtrip", CoreTestCases.TestEncryptedSettingsRoundtrip),
        new TestCase("Usable access token is reused", CoreTestCases.TestUsableAccessTokenIsReused),
        new TestCase("Expired access token refreshes first", CoreTestCases.TestExpiredAccessTokenRefreshesFirst),
        new TestCase("Rejected refresh falls back to login", CoreTestCases.TestRejectedRefreshFallsBackToLogin),
        new TestCase("Refresh API code falls back to login", CoreTestCases.TestRefreshApiCodeFallsBackToLogin),
        new TestCase("HTTP 200 failure status overrides success code", CoreTestCases.TestHttp200FailureStatusOverridesSuccessCode),
        new TestCase("HTTP 200 failure status falls back to login", CoreTestCases.TestHttp200FailureStatusFallsBackToLogin),
        new TestCase("HTTP 200 specific failure code falls back to login", CoreTestCases.TestHttp200SpecificFailureCodeFallsBackToLogin),
        new TestCase("Refresh network failure does not log in", CoreTestCases.TestRefreshNetworkFailureDoesNotLogIn),
        new TestCase("Authentication API code is classified", CoreTestCases.TestAuthenticationApiCodeIsClassified),
        new TestCase("Login endpoint maps session", CoreTestCases.TestLoginEndpointMapsSession),
        new TestCase("Refresh endpoint maps rotated session", CoreTestCases.TestRefreshEndpointMapsRotatedSession),
        new TestCase("Refresh keeps token when server omits rotation", CoreTestCases.TestRefreshKeepsTokenWhenServerOmitsRotation),
        new TestCase("HTTP 200 success envelopes deserialize", CoreTestCases.TestHttp200SuccessEnvelopesDeserialize),
        new TestCase("HTTP 200 direct business responses deserialize", CoreTestCases.TestHttp200DirectBusinessResponsesDeserialize),
        new TestCase("HTTP 200 direct JsonElement validation response remains usable", CoreTestCases.TestHttp200DirectJsonElementValidationResponseRemainsUsable),
        new TestCase("HTTP 200 envelopes reject explicit business errors", CoreTestCases.TestHttp200EnvelopeRejectsExplicitBusinessErrors),
        new TestCase("HTTP 200 envelope uses nested error code", CoreTestCases.TestHttp200EnvelopeUsesNestedErrorCode),
        new TestCase("HTTP 200 envelope rejects malformed or missing payload", CoreTestCases.TestHttp200EnvelopeRejectsMalformedOrMissingPayload),
        new TestCase("HTTP 200 envelope safe presentation hides successful status", CoreTestCases.TestHttp200EnvelopeSafePresentationHidesSuccessfulStatus),
        new TestCase("Authentication error hides server message", CoreTestCases.TestAuthenticationErrorHidesServerMessage),
        new TestCase("Business error hides server message", CoreTestCases.TestBusinessErrorHidesServerMessage),
        new TestCase("Authentication statuses have safe diagnostics", CoreTestCases.TestAuthenticationStatusesHaveSafeDiagnostics),
        new TestCase("Business authentication statuses keep business diagnostics", CoreTestCases.TestBusinessAuthenticationStatusesKeepBusinessDiagnostics),
        new TestCase("Malformed authentication responses retain endpoint context", CoreTestCases.TestMalformedAuthenticationResponsesRetainEndpointContext),
        new TestCase("Unknown errors do not expose credential text", CoreTestCases.TestUnknownErrorsDoNotExposeCredentialText),
        new TestCase("Interactive login requirement is rejected", CoreTestCases.TestInteractiveLoginRequirementIsRejected),
        new TestCase("Empty key selection roundtrips", CoreTestCases.TestEmptyKeySelectionRoundtrips),
        new TestCase("First key selection chooses first active key", CoreTestCases.TestFirstKeySelectionChoosesFirstActiveKey),
        new TestCase("Initialized empty key selection stays empty", CoreTestCases.TestInitializedEmptyKeySelectionStaysEmpty),
        new TestCase("Routing UI settings normalize safely", CoreTestCases.TestRoutingUiSettingsNormalize),
        new TestCase("Routing UI settings compare normalized snapshots", CoreTestCases.TestRoutingUiSettingsEquivalentToNormalizedSnapshot),
        new TestCase("Routing persistence policy suppresses batch writes", CoreTestCases.TestRoutingPersistencePolicySuppressesBatchWrites));

    public static IReadOnlyList<TestCase> Create(params TestCase[] tests)
    {
        var names = new HashSet<string>(StringComparer.Ordinal);
        foreach (var test in tests)
        {
            if (!names.Add(test.Name))
            {
                throw new InvalidOperationException($"Duplicate test name: {test.Name}.");
            }
        }

        return Array.AsReadOnly(tests.ToArray());
    }
}
